version: '3.7'
services:
# DATA_BASE**********************************
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: quizter_db
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=quizter
    restart: unless-stopped
# APP*****************************************
  quizter_app:
    image: quizter_app:latest
    network_mode: bridge
    container_name: quizter_app
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres